dist: trusty
sudo: required
language: go

env:
  - DEP_VERSION="0.5.0"

services:
  - docker

before_install:
  # Install docker
  - sudo apt-get remove docker docker-engine docker.io
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo apt-get update
  - sudo apt-get install -y docker-ce
  - docker version
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep

install:
  - dep ensure
  - docker build -t gonvey .

notifications:
  email:
    recipients:
      - brendan.le-glaunec@epitech.eu
    on_success: never
    on_failure: always
