version: '3.1'

services:

  gonvey:
    build: .
    environment:
      - GONVEY_LOG_LEVEL=DEBUG
      - GONVEY_SERVER_PORT=8888
      - GONVEY_PROXY_MAP={"/bloggo":["http://app1:4242"]}
    ports:
      - 8888:8888
    depends_on:
      - app1
      - app2
      - app3
      - app4

  # The 4 endpoints are simple http servers that take a port
  # and return 404 to everything that makes request
  app1:
    image: ullaakut/simplehttptest
    ports:
      - 4242:4242
    environment:
      - PORT=4242

  app2:
    image: ullaakut/simplehttptest
    ports:
      - 4243:4243
    environment:
      - PORT=4243

  app3:
    image: ullaakut/simplehttptest
    ports:
      - 4244:4244
    environment:
      - PORT=4244

  app4:
    image: ullaakut/simplehttptest
    ports:
      - 4245:4245
    environment:
      - PORT=4245
