{
 "title": "Gonvey",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Requests per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count[15s])) by (http_request_uri)",
     "legendFormat": "{{http_request_uri}}"
    }
   ]
  },
  {
   "title": "Requests per second per endpoint",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_count[1m])) by (endpoint)",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "HTTP Response Status Codes per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(http_response_code[15s])", "legendFormat": "{{http_response_code}}" }
   ]
  },
  {
   "title": "Average response time (ms)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(http_response_time_seconds_sum[15s]) / rate(http_response_time_seconds_count[15s])) / 1000000",
     "legendFormat": "Over the last 15s"
    },
    {
     "expr": "(rate(http_response_time_seconds_sum[15m]) / rate(http_response_time_seconds_count[15m])) / 1000000",
     "legendFormat": "Over the last 15m"
    },
    {
     "expr": "(rate(http_response_time_seconds_sum[15h]) / rate(http_response_time_seconds_count[15h])) / 1000000",
     "legendFormat": "Over the last 15h"
    }
   ]
  },
  {
   "title": "Goroutines per job",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Memory usage per job (%)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes / go_memstats_alloc_bytes_total",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Total number of HTTP requests proxied",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "sum(http_requests_count)" }
   ]
  }
 ]
}